### ISSUE TITLE
Python 3.12 installation crash

### ISSUE THREAD

**Issue by AlexKurek** [ratt-ru/shadeMS#124]
`shadems` needs `datashape`:
`Collecting datashape (from datashader<0.16.0,>=0.15.0->shadems==0.5.3->-r /opt/lofar/requirements3.txt (line 38))`
`datashape` is not compatibile with Python 3.12:
https://github.com/blaze/datashape/issues/245

(This is an upstream of https://github.com/tikk3r/flocs/issues/100#issuecomment-2543192437).

**Comment by AlexKurek** [comment]
I dont think its getting fixed, last commit was ~5y ago.
BTW `datashader` now supports Python 3.12: https://github.com/holoviz/datashader/releases/tag/v0.16.1

**Comment by o-smirnov** [comment]
Hmmm, I'm confused where ``datashader<0.16.0`` comes from then, we don't have an upper version pin in ``pyproject.toml``. @Athanaseus any idea?

**Comment by Athanaseus** [comment]
Hi @o-smirnov ,

This is because the caret (^) in semantic versioning (`datashader = "^0.15.0"`) allows updates within the minor version range for versions below `1.0.0`. 
Valid versions: `0.15.0, 0.15.1, 0.15.2`, etc., up to but not including `0.16.0`.

Indeed, `0.16.1` supports `Py3.12` and dropped `Py3.8`.
@AlexKurek please try with `issue-124` branch.

Best regards

**Comment by AlexKurek** [comment]
I checked, it works:

```
Collecting git+https://github.com/ratt-ru/shadeMS.git@issue-124 (from -r /opt/lofar/requirements3.txt (line 38))
  Cloning https://github.com/ratt-ru/shadeMS.git (to revision issue-124) to /tmp/pip-req-build-yfwbbl1g
  Running command git clone --filter=blob:none --quiet https://github.com/ratt-ru/shadeMS.git /tmp/pip-req-build-yfwbbl1g
  Running command git checkout -b issue-124 --track origin/issue-124
  Switched to a new branch 'issue-124'
  branch 'issue-124' set up to track 'origin/issue-124'.
  Resolved https://github.com/ratt-ru/shadeMS.git to commit acf3433efda97aefb5cfe3cff4d55114aa9b420c
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
```

**Comment by o-smirnov** [comment]
> Hi @o-smirnov ,
> 
> This is because the caret (^) in semantic versioning (`datashader = "^0.15.0"`) allows updates within the minor version range for versions below `1.0.0`. 

Thanks! I learn something new every day.

**Comment by AlexKurek** [comment]
Tagging @tikk3r

**Comment by tikk3r** [comment]
After #128 it installs ok for me on Python 3.12 via e.g.
```bash
pip install --upgrade -t daskpython shadems
<snip>
Successfully installed Jinja2-3.1.5 MarkupSafe-3.0.2 PyYAML-6.0.2 appdirs-1.4.4 bleach-6.2.0 bokeh-3.6.2 certifi-2024.12.14 charset-normalizer-3.4.1 click-8.1.8 cloudpickle-3.1.1 cmasher-1.9.2 colorcet-3.1.0 colorspacious-1.1.2 contourpy-1.3.1 cycler-0.12.1 dask-2024.10.0 dask-ms-0.2.23 datashader-0.16.3 donfig-0.8.1.post1 fonttools-4.55.6 fsspec-2024.12.0 future-fstrings-1.2.0 holoviews-1.20.0 idna-3.10 kiwisolver-1.4.8 linkify-it-py-2.0.3 llvmlite-0.44.0 locket-1.0.0 markdown-3.7 markdown-it-py-3.0.0 matplotlib-3.10.0 mdit-py-plugins-0.4.2 mdurl-0.1.2 multipledispatch-1.0.0 numba-0.61.0 numpy-2.1.3 packaging-24.2 pandas-2.2.3 panel-1.6.0 param-2.2.0 partd-1.4.2 pillow-11.1.0 pyct-0.5.0 pyparsing-3.2.1 python-casacore-3.6.1 python-dateutil-2.9.0.post0 pytz-2024.2 pyviz-comms-3.0.4 requests-2.32.3 scipy-1.15.1 shadems-0.5.4 six-1.17.0 toolz-1.0.0 tornado-6.4.2 tqdm-4.67.1 typing-extensions-4.12.2 tzdata-2025.1 uc-micro-py-1.0.3 urllib3-2.3.0 webencodings-0.5.1 xarray-2025.1.1 xyzservices-2025.1.0
```

but sadly it crashes when trying to run it:

```python
(pyenv-py3) shadems --xaxis TIME --yaxis DATA:amp:XX test.ms/
<snip>
2025-01-26 21:57:13 - shadems - INFO - : Indexing MS and building dataframes (27750 rows, chunk size is 5000)
Traceback (most recent call last):
  File "/home/lofarvwf-fsweijen/containers/./daskpython/bin/shadems", line 8, in <module>
    sys.exit(driver())
             ^^^^^^^^
  File "/home/lofarvwf-fsweijen/containers/daskpython/shade_ms/main.py", line 578, in driver
    main([a for a in sys.argv[1:]])
  File "/home/lofarvwf-fsweijen/containers/daskpython/shade_ms/main.py", line 419, in main
    data_plots.get_plot_data(ms, group_cols, mytaql, ms.chan_freqs,
  File "/home/lofarvwf-fsweijen/containers/daskpython/shade_ms/data_plots.py", line 216, in get_plot_data
    df1 = dataframe_factory(("row", "chan"), *args, columns=arrays.keys())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lofarvwf-fsweijen/containers/daskpython/shade_ms/dask_utils.py", line 143, in dataframe_factory
    return dd.DataFrame(graph, name, meta=meta, divisions=divisions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: FrameBase.__init__() got an unexpected keyword argument 'meta'
```

**Comment by sjperkins** [comment]
`pip install -t` installs into an existing venv. Can you please try again in a fresh venv (say `shadems`) which should only contain the shade-ms install?

**Comment by tikk3r** [comment]
> > but sadly it crashes when trying to run it:
> 
> `pip install -t` installs into an existing venv. Can you please try again in a fresh venv (say `shadems`) which should only contain the shade-ms install?

Ah I thought a target directory would evade an active venv  given the amount of dependencies it seemed to install in there. Creating a new venv does yield a working installation.

```bash
virtualenv newenv
source newenv/bin/activate
(newenv) pip install shadems
(newenv) shadems --xaxis TIME --yaxis DATA:amp:XX test.ms/
/home/lofarvwf-fsweijen/containers/newenv/lib/python3.12/site-packages/dask/dataframe/__init__.py:42: FutureWarning: 
Dask dataframe query planning is disabled because dask-expr is not installed.

You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.

  warnings.warn(msg, FutureWarning)
2025-01-27 10:52:30 - shadems - INFO - using colourmap colorcet.bkr
2025-01-27 10:52:30 - shadems - INFO - using colourmap cmasher.pride
2025-01-27 10:52:30 - shadems - INFO - using colourmap colorcet.glasbey_dark
2025-01-27 10:52:30 - shadems - INFO - /home/lofarvwf-fsweijen/containers/newenv/bin/shadems --xaxis TIME --yaxis DATA:amp:XX test.ms/
2025-01-27 10:52:30 - shadems - INFO - ------------------------------------------------------
2025-01-27 10:52:30 - shadems - INFO - : MS test.ms contains 27750 rows
2025-01-27 10:52:31 - shadems - INFO - :   (1, 10) spectral windows and channels
2025-01-27 10:52:31 - shadems - INFO - :   1 fields: BEAM_2
2025-01-27 10:52:31 - shadems - INFO - :   1 scans: 0
2025-01-27 10:52:31 - shadems - INFO - :   75/75 antennas: 0:CS001HBA0 1:CS001HBA1 2:CS002HBA0 3:CS002HBA1 4:CS003HBA0 5:CS003HBA1 6:CS004HBA0 7:CS004HBA1 8:CS005HBA0 9:CS005HBA1 10:CS006HBA0 11:CS006HBA1 12:CS007HBA0 13:CS007HBA1 14:CS011HBA0 15:CS011HBA1 16:CS013HBA0 17:CS013HBA1 18:CS017HBA0 19:CS017HBA1 20:CS021HBA0 21:CS021HBA1 22:CS024HBA0 23:CS024HBA1 24:CS026HBA0 25:CS026HBA1 26:CS028HBA0 27:CS028HBA1 28:CS030HBA0 29:CS030HBA1 30:CS031HBA0 31:CS031HBA1 32:CS032HBA0 33:CS032HBA1 34:CS101HBA0 35:CS101HBA1 36:CS103HBA0 37:CS103HBA1 38:CS201HBA0 39:CS201HBA1 40:CS301HBA0 41:CS301HBA1 42:CS302HBA0 43:CS302HBA1 44:CS401HBA0 45:CS401HBA1 46:CS501HBA0 47:CS501HBA1 48:RS106HBA 49:RS205HBA 50:RS208HBA 51:RS210HBA 52:RS305HBA 53:RS306HBA 54:RS307HBA 55:RS310HBA 56:RS406HBA 57:RS407HBA 58:RS409HBA 59:RS503HBA 60:RS508HBA 61:RS509HBA 62:DE601HBA 63:DE602HBA 64:DE603HBA 65:DE604HBA 66:DE605HBA 67:FR606HBA 68:SE607HBA 69:UK608HBA 70:DE609HBA 71:PL610HBA 72:PL611HBA 73:PL612HBA 74:IE613HBA
2025-01-27 10:52:31 - shadems - INFO - :   2775/2850 baselines present
2025-01-27 10:52:32 - shadems - INFO - :   corrs/Stokes XX XY YX YY I Q U V
2025-01-27 10:52:32 - shadems - INFO - ------------------------------------------------------
2025-01-27 10:52:32 - shadems - INFO - : Data selected for plotting:
2025-01-27 10:52:32 - shadems - INFO - Antenna(s)       : all
2025-01-27 10:52:32 - shadems - INFO - Baseline(s)      : all except autocorrelations
2025-01-27 10:52:32 - shadems - INFO - Field(s)         : all
2025-01-27 10:52:32 - shadems - INFO - SPW(s)           : all
2025-01-27 10:52:32 - shadems - INFO - Scan(s)          : all
2025-01-27 10:52:32 - shadems - INFO - Channels         : all
2025-01-27 10:52:32 - shadems - INFO - Corr/Stokes      : XX XY YX YY
2025-01-27 10:52:32 - shadems - INFO - ------------------------------------------------------
2025-01-27 10:52:32 - shadems - INFO - loading minmax cache from test-minmax-cache.json
2025-01-27 10:52:32 - shadems - INFO - axis: TIME(TIME), range (None, None), discretization None
2025-01-27 10:52:32 - shadems - INFO - axis: amp(DATA), corr 0, range (None, None), discretization None
2025-01-27 10:52:32 - shadems - INFO -                  : you have asked for 1 plots employing 2 unique datums
2025-01-27 10:52:32 - shadems - INFO - : Indexing MS and building dataframes (27750 rows, chunk size is 5000)
2025-01-27 10:52:32 - shadems - INFO - : complete
2025-01-27 10:52:32 - shadems - INFO - : rendering 1 dataframes with 1.11e+06 points into 1 plot types
2025-01-27 10:52:32 - shadems - INFO - : rendering plot-test-DATA-XX-amp-TIME.png
2025-01-27 10:52:32 - shadems - INFO - : scanning axis min/max for TIME_TIME_False DATA_amp_0
2025-01-27 10:52:34 - shadems - INFO -                  : wrote plot-test-DATA-XX-amp-TIME.png
2025-01-27 10:52:34 - shadems - INFO - Total time       : 3.94 seconds
2025-01-27 10:52:34 - shadems - INFO - Saved minmax cache to test-minmax-cache.json (disable with --no-lim-save)
2025-01-27 10:52:34 - shadems - INFO - Finished
2025-01-27 10:52:34 - shadems - INFO - ------------------------------------------------------
```
Thanks. I'll do some more digging in what is causing conflicts in my environment then as my dask version should match the requirements...

**Comment by sjperkins** [comment]
I would guess the cause is discussed in the following comment:

- https://github.com/ratt-ru/shadeMS/issues/126#issuecomment-2612544724

Sometimes there's a desire to install multiple applications in a venv, but this frequently leads to dependency hell

https://en.wikipedia.org/wiki/Dependency_hell

**Comment by tikk3r** [comment]
> I would guess the cause is discussed in the following comment:
> 
>     * [shadems / dask-ms / NumPy 2.0 installation causing tons of problems #126 (comment)](https://github.com/ratt-ru/shadeMS/issues/126#issuecomment-2612544724)
> 
> 
> Sometimes there's a desire to install multiple applications in a venv, but this frequently leads to dependency hell
> 
> https://en.wikipedia.org/wiki/Dependency_hell

Yeah dependency hell is a real pain. I would have liked to avoid multiple venvs, but it looks like for shadeMS I'll have to go that route for now.
