### ISSUE TITLE
cmap error on current master

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/shadeMS#24]
```
shadems --xaxis uv --yaxis DATA:a:XX 1559762398_sdp_l0.full_1284.full_pol_wtspec_GLEAMJ164604-222756.ms
2020-04-18 17:10:30 - INFO     - ------------------------------------------------------
2020-04-18 17:10:30 - INFO     -                  : MS is 1559762398_sdp_l0.full_1284.full_pol_wtspec_GLEAMJ164604-222756.ms
2020-04-18 17:10:30 - INFO     -                  :   (1, 1024) spectral windows and channels
2020-04-18 17:10:30 - INFO     -                  :   1 fields: GLEAMJ164604-222756
2020-04-18 17:10:30 - INFO     -                  :   1 scans, first #29, last #29
2020-04-18 17:10:30 - INFO     -                  :   58 antennas: 0:m000 1:m001 2:m002 3:m003 4:m004 5:m005 6:m006 7:m007 8:m008 9:m009 10:m010 11:m011 12:m012 13:m013 14:m014 15:m015 16:m016 17:m018 18:m019 19:m020 20:m021 21:m022 22:m023 23:m024 24:m025 25:m026 26:m027 27:m028 28:m029 29:m030 30:m031 31:m032 32:m033 33:m034 34:m035 35:m037 36:m038 37:m040 38:m041 39:m042 40:m043 41:m044 42:m045 43:m046 44:m047 45:m048 46:m049 47:m050 48:m051 49:m052 50:m053 51:m056 52:m057 53:m058 54:m059 55:m060 56:m061 57:m062
2020-04-18 17:10:30 - INFO     -                  :   correlations XX XY YX YY
2020-04-18 17:10:30 - INFO     - ------------------------------------------------------
2020-04-18 17:10:30 - INFO     - Antenna(s)       : all
2020-04-18 17:10:30 - INFO     - Field(s)         : all
2020-04-18 17:10:30 - INFO     - SPW(s)           : all
2020-04-18 17:10:30 - INFO     - Scan(s)          : all
2020-04-18 17:10:30 - INFO     - ------------------------------------------------------
2020-04-18 17:10:30 - INFO     - defining new plot axis: uv of UVW corr False, clip (None, None), discretization None
2020-04-18 17:10:30 - INFO     - defining new plot axis: a of DATA corr 0, clip (None, None), discretization None
2020-04-18 17:10:30 - INFO     -                  : you have asked for 1 plots employing 2 unique datums
2020-04-18 17:10:30 - INFO     -                  : Indexing MS and building dataframes
2020-04-18 17:10:30 - INFO     -                  : complete
2020-04-18 17:10:30 - INFO     -                  : rendering 1 dataframes with 6.48e+07 points into 1 plot types
2020-04-18 17:10:30 - INFO     -                  : rendering plot-1559762398_sdp_l0.full_1284.full_pol_wtspec_GLEAMJ164604-222756-DATA_XX_a_uv.png
Traceback (most recent call last):
  File "/users/ianh/venv/shadems/bin/shadems", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/users/ianh/Software/shadeMS/bin/shadems", line 8, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/users/ianh/Software/shadeMS/ShadeMS/main.py", line 501, in main
    render_single_plot(df, xmap, ymap, cmap, pngname, title, xlabel, ylabel)
  File "/users/ianh/Software/shadeMS/ShadeMS/main.py", line 466, in render_single_plot
    figx=xcanvas / 60, figy=ycanvas / 60)
  File "/users/ianh/Software/shadeMS/ShadeMS/shadeMS.py", line 464, in create_plot
    img = datashader.transfer_functions.shade(raster, cmap=cmap, how=normalize)
  File "/users/ianh/venv/shadems/lib/python3.6/site-packages/datashader/transfer_functions/__init__.py", line 447, in shade
    return _interpolate(agg, cmap, how, alpha, span, min_alpha, name)
  File "/users/ianh/venv/shadems/lib/python3.6/site-packages/datashader/transfer_functions/__init__.py", line 312, in _interpolate
    "`list`, `str`, or `tuple`; got: '{0}'".format(type(cmap)))
TypeError: Expected `cmap` of `matplotlib.colors.Colormap`, `list`, `str`, or `tuple`; got: '<class 'NoneType'>'
```

**Comment by o-smirnov** [comment]
Yeah typical. So busy testing colors, I broke the no-color mode and never noticed.

Try my branch...
