### ISSUE TITLE
Time axis only available by requesting TIME_CENTROID

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/shadeMS#30]
I could only get a plot featuring a time axis by requesting the TIME_CENTROID column.

This took some figuring out and is a bit unfriendly, but why doesn't asking for the TIME column work?

```
$ shadems --field 0 -x TIME -y CORRECTED_DATA:amp:XX 1559762398_sdp_l0.full_1284.full_pol_wtspec.ms
2020-04-19 11:14:45 - INFO     - ------------------------------------------------------
2020-04-19 11:14:45 - INFO     -                  : MS is 1559762398_sdp_l0.full_1284.full_pol_wtspec.ms
2020-04-19 11:14:46 - INFO     -                  :   (1, 1024) spectral windows and channels
2020-04-19 11:14:46 - INFO     -                  :   41 fields: PKS1934-63 J1331+3030 J1150-0023 GLEAMJ121740+033940 GLEAMJ132606-272641 GLEAMJ133224-330824 GLEAMJ134855-252700 GLEAMJ135119-054857 J1427-4206 GLEAMJ140421-340018 GLEAMJ144635-084544 GLEAMJ145423-192504 GLEAMJ145509-365543 GLEAMJ150638-765415 GLEAMJ152132-400059 GLEAMJ152659-135059 GLEAMJ153014-423146 GLEAMJ155855-213608 GLEAMJ160237+154416 J1517-2422 GLEAMJ160559-362226 GLEAMJ161321-771943 GLEAMJ162033-710017 GLEAMJ162249-282314 GLEAMJ163134-750952 J1605-1734 GLEAMJ164524-183511 GLEAMJ164604-222756 GLEAMJ165258+001908 GLEAMJ165712-134911 GLEAMJ172042-011048 J1733-1304 GLEAMJ172438-024205 GLEAMJ173119+210454 GLEAMJ174146+060201 GLEAMJ174630+234252 GLEAMJ175726+073127 GLEAMJ175825+082837 GLEAMJ181231+262922 GLEAMJ183531+273208 J1609+2641
2020-04-19 11:14:46 - INFO     -                  :   44 scans, first #1, last #44
2020-04-19 11:14:46 - INFO     -                  :   58 antennas: 0:m000 1:m001 2:m002 3:m003 4:m004 5:m005 6:m006 7:m007 8:m008 9:m009 10:m010 11:m011 12:m012 13:m013 14:m014 15:m015 16:m016 17:m018 18:m019 19:m020 20:m021 21:m022 22:m023 23:m024 24:m025 25:m026 26:m027 27:m028 28:m029 29:m030 30:m031 31:m032 32:m033 33:m034 34:m035 35:m037 36:m038 37:m040 38:m041 39:m042 40:m043 41:m044 42:m045 43:m046 44:m047 45:m048 46:m049 47:m050 48:m051 49:m052 50:m053 51:m056 52:m057 53:m058 54:m059 55:m060 56:m061 57:m062
2020-04-19 11:14:46 - INFO     -                  :   correlations XX XY YX YY
2020-04-19 11:14:46 - INFO     - ------------------------------------------------------
2020-04-19 11:14:46 - INFO     - Antenna(s)       : all
2020-04-19 11:14:46 - INFO     - Field(s)         : PKS1934-63
2020-04-19 11:14:46 - INFO     - SPW(s)           : all
2020-04-19 11:14:46 - INFO     - Scan(s)          : all
2020-04-19 11:14:46 - INFO     - ------------------------------------------------------
2020-04-19 11:14:46 - INFO     - defining new plot axis: TIME of TIME corr False, clip (None, None), discretization None
2020-04-19 11:14:46 - INFO     - defining new plot axis: amp of CORRECTED_DATA corr 0, clip (None, None), discretization None
2020-04-19 11:14:46 - INFO     -                  : you have asked for 1 plots employing 2 unique datums
2020-04-19 11:14:47 - INFO     -                  : Indexing MS and building dataframes
Traceback (most recent call last):
  File "/users/ianh/venv/shadems/bin/shadems", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/users/ianh/Software/shadeMS/bin/shadems", line 8, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/users/ianh/Software/shadeMS/ShadeMS/main.py", line 427, in main
    row_chunk_size=options.row_chunk_size)
  File "/users/ianh/Software/shadeMS/ShadeMS/shadeMS.py", line 379, in get_plot_data
    value = axis.get_value(group, corr, extras, flag, flag_row)
  File "/users/ianh/Software/shadeMS/ShadeMS/shadeMS.py", line 269, in get_value
    coldata = self.mapper.mapper(coldata, **{name:extras[name] for name in self.mapper.extras })
TypeError: 'NoneType' object is not callable
Error shutting down executor: 'NoneType' object is not callable
```

```
$ shadems --field 0 -x TIME_CENTROID -y CORRECTED_DATA:amp:XX 1559762398_sdp_l0.full_1284.full_pol_wtspec.ms
2020-04-19 11:13:14 - INFO     - ------------------------------------------------------
2020-04-19 11:13:14 - INFO     -                  : MS is 1559762398_sdp_l0.full_1284.full_pol_wtspec.ms
2020-04-19 11:13:14 - INFO     -                  :   (1, 1024) spectral windows and channels
2020-04-19 11:13:14 - INFO     -                  :   41 fields: PKS1934-63 J1331+3030 J1150-0023 GLEAMJ121740+033940 GLEAMJ132606-272641 GLEAMJ133224-330824 GLEAMJ134855-252700 GLEAMJ135119-054857 J1427-4206 GLEAMJ140421-340018 GLEAMJ144635-084544 GLEAMJ145423-192504 GLEAMJ145509-365543 GLEAMJ150638-765415 GLEAMJ152132-400059 GLEAMJ152659-135059 GLEAMJ153014-423146 GLEAMJ155855-213608 GLEAMJ160237+154416 J1517-2422 GLEAMJ160559-362226 GLEAMJ161321-771943 GLEAMJ162033-710017 GLEAMJ162249-282314 GLEAMJ163134-750952 J1605-1734 GLEAMJ164524-183511 GLEAMJ164604-222756 GLEAMJ165258+001908 GLEAMJ165712-134911 GLEAMJ172042-011048 J1733-1304 GLEAMJ172438-024205 GLEAMJ173119+210454 GLEAMJ174146+060201 GLEAMJ174630+234252 GLEAMJ175726+073127 GLEAMJ175825+082837 GLEAMJ181231+262922 GLEAMJ183531+273208 J1609+2641
2020-04-19 11:13:14 - INFO     -                  :   44 scans, first #1, last #44
2020-04-19 11:13:15 - INFO     -                  :   58 antennas: 0:m000 1:m001 2:m002 3:m003 4:m004 5:m005 6:m006 7:m007 8:m008 9:m009 10:m010 11:m011 12:m012 13:m013 14:m014 15:m015 16:m016 17:m018 18:m019 19:m020 20:m021 21:m022 22:m023 23:m024 24:m025 25:m026 26:m027 27:m028 28:m029 29:m030 30:m031 31:m032 32:m033 33:m034 34:m035 35:m037 36:m038 37:m040 38:m041 39:m042 40:m043 41:m044 42:m045 43:m046 44:m047 45:m048 46:m049 47:m050 48:m051 49:m052 50:m053 51:m056 52:m057 53:m058 54:m059 55:m060 56:m061 57:m062
2020-04-19 11:13:15 - INFO     -                  :   correlations XX XY YX YY
2020-04-19 11:13:15 - INFO     - ------------------------------------------------------
2020-04-19 11:13:15 - INFO     - Antenna(s)       : all
2020-04-19 11:13:15 - INFO     - Field(s)         : PKS1934-63
2020-04-19 11:13:15 - INFO     - SPW(s)           : all
2020-04-19 11:13:15 - INFO     - Scan(s)          : all
2020-04-19 11:13:15 - INFO     - ------------------------------------------------------
2020-04-19 11:13:15 - INFO     - defining new plot axis: _ of TIME_CENTROID corr False, clip (None, None), discretization None
2020-04-19 11:13:15 - INFO     - defining new plot axis: amp of CORRECTED_DATA corr 0, clip (None, None), discretization None
2020-04-19 11:13:15 - INFO     -                  : you have asked for 1 plots employing 2 unique datums
2020-04-19 11:13:15 - INFO     -                  : Indexing MS and building dataframes
2020-04-19 11:13:15 - INFO     -                  : complete
2020-04-19 11:13:15 - INFO     -                  : rendering 1 dataframes with 1.3e+08 points into 1 plot types
2020-04-19 11:13:15 - INFO     -                  : rendering plot-1559762398_sdp_l0.full_1284.full_pol_wtspec-PKS1934-63-CORRECTED_DATA_XX_amp_TIME_CENTROID.png
2020-04-19 11:14:20 - INFO     -                  : wrote plot-1559762398_sdp_l0.full_1284.full_pol_wtspec-PKS1934-63-CORRECTED_DATA_XX_amp_TIME_CENTROID.png
2020-04-19 11:14:20 - INFO     - Total time       : 65.84 seconds
2020-04-19 11:14:20 - INFO     - Finished
2020-04-19 11:14:20 - INFO     - ------------------------------------------------------
```

**Comment by o-smirnov** [comment]
My bad. The usual cleanup breakage...

**Comment by o-smirnov** [comment]
BTW, fun fact, did you realize you can color by chunks of band? Try e.g.
```
-c CHAN --cmin 0 --cmax 1024 --cnum 16 --bmap glasbey_dark
```
