### ISSUE TITLE
Invalid index error related to scan numbers

### ISSUE THREAD

**Issue by ulricharmel** [ratt-ru/shadeMS#33]
(shadems) ulrich@jake:/net/tina/vault-tina/ulrich/MeerKAT-rooibos/plots-shadems$ shadems --xaxis FREQ,CHAN --yaxis DATA:amp,DATA:amp ../1558752655_sdp_l0.full_1284.full_pol-4C12_02_corr.ms
2020-04-21 14:11:57 - INFO     - /home/ulrich/venv/shadems/bin/shadems --xaxis FREQ,CHAN --yaxis DATA:amp,DATA:amp ../1558752655_sdp_l0.full_1284.full_pol-4C12_02_corr.ms
2020-04-21 14:11:57 - INFO     - ------------------------------------------------------
2020-04-21 14:11:57 - INFO     -                  : MS ../1558752655_sdp_l0.full_1284.full_pol-4C12_02_corr.ms contains 2624832 rows
2020-04-21 14:11:57 - INFO     -                  :   (1, 1024) spectral windows and channels
2020-04-21 14:11:57 - INFO     -                  :   1 fields: 4C12.02
2020-04-21 14:11:58 - INFO     -                  :   12 scans, first #2, last #31
Traceback (most recent call last):
  File "/home/ulrich/venv/shadems/bin/shadems", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/ulrich/venv/shadems/shadeMS/bin/shadems", line 8, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/home/ulrich/venv/shadems/shadeMS/ShadeMS/main.py", line 285, in main
    ms = sms.ms = MSInfo(options.ms, log=log)
  File "/home/ulrich/venv/shadems/shadeMS/ShadeMS/ms_info.py", line 82, in __init__
    self.scan = all_scans.get_subset(scan_numbers)
  File "/home/ulrich/venv/shadems/shadeMS/ShadeMS/ms_info.py", line 30, in get_subset
    return NamedList(self.label, [self.names[x] for x in subset], subset)
  File "/home/ulrich/venv/shadems/shadeMS/ShadeMS/ms_info.py", line 30, in <listcomp>
    return NamedList(self.label, [self.names[x] for x in subset], subset)
IndexError: list index out of range

I get the above error which I am suspecting is related to the scan numbers in this ms which are  [2, 36, 6, 40, 10, 44, 14, 48, 19, 23, 27, 31] 
Here is the branch I used: https://github.com/IanHeywood/shadeMS/tree/harlequin

**Comment by o-smirnov** [comment]
Yep, you're right, there was a sort operation missing.

Could you please try the ``fourth-wall`` branch now?

**Comment by ulricharmel** [comment]
I am getting a different error now
Traceback (most recent call last):
  File "/home/ulrich/venv/shadems/bin/shadems", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/ulrich/venv/shadems/shadeMS/bin/shadems", line 6, in <module>
    from shade_ms import main
  File "/home/ulrich/venv/shadems/shadeMS/shade_ms/main.py", line 23, in <module>
    from . import data_plots, data_mappers
  File "/home/ulrich/venv/shadems/shadeMS/shade_ms/data_plots.py", line 232, in <module>
    class extract_multi(datashader.reductions.category_values):
AttributeError: module 'datashader.reductions' has no attribute 'category_values'

**Comment by o-smirnov** [comment]
Ah. Install the master version of dstashader from github. I'll take out
that dependence tomorrow.

Cheers,
Oleg

---
Sent from my phone. Quality of spelling inversely proportional to finger
size.

**Comment by ulricharmel** [comment]
It is running now. I have screened it. I will check the result in the morning.
