### ISSUE TITLE
Chunks do not align error

### ISSUE THREAD

**Issue by JonahDW** [ratt-ru/shadeMS#50]
Just installed the latest shadeMS version, and decided to try a not too complicated plot on a ~40GB MeerKAT dataset:

`shadems --xaxis FREQ --yaxis CORRECTED_DATA:amp --colour-by BASELINE J1833chav32.ms`

While building the dataframes, it throws the following dask error:
```
Traceback (most recent call last):
  File "/homes/wagenveld/anaconda3/bin/shadems", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/.aux_mnt/pc002a/wagenveld/MeerKAT/MS_PlotTools/shadeMS/bin/shadems", line 8, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/.aux_mnt/pc002a/wagenveld/MeerKAT/MS_PlotTools/shadeMS/shade_ms/main.py", line 548, in main
    row_chunk_size=options.row_chunk_size)
  File "/.aux_mnt/pc002a/wagenveld/MeerKAT/MS_PlotTools/shadeMS/shade_ms/data_plots.py", line 147, in get_plot_data
    da.broadcast_arrays(*datums.values()))})
  File "/homes/wagenveld/anaconda3/lib/python3.7/site-packages/dask/array/core.py", line 4016, in broadcast_arrays
    chunks = broadcast_chunks(*(e.chunks for e in args))
  File "/homes/wagenveld/anaconda3/lib/python3.7/site-packages/dask/array/core.py", line 779, in broadcast_chunks
    raise ValueError("Chunks do not align: %s" % str(step2))
ValueError: Chunks do not align: [(602784, 602784), (100000, 100000, 100000, 100000, 100000, 100000, 2784, 100000, 100000, 100000, 100000, 100000, 100000, 2784), (100000, 100000, 100000, 100000, 100000, 100000, 2784, 100000, 100000, 100000, 100000, 100000, 100000, 2784)]
```

**Comment by IanHeywood** [comment]
Did you drop completely flagged rows when the MS was averaged / split?

**Comment by JonahDW** [comment]
They might have been dropped, the MS had already been averaged and split when I received it. However I did not have this issue (with this dataset) in an earlier release of shadeMS a couple of weeks ago.

**Comment by sjperkins** [comment]
Smells like three arrays broadcast against each other, the first's chunking schema being different from the last two. They need to be the same. I think the sum of each tuple (the shape) is the same.

```traceback
ValueError: Chunks do not align: [(602784, 602784), (100000, 100000, 100000, 100000, 100000, 100000, 2784, 100000, 100000, 100000, 100000, 100000, 100000, 2784), (100000, 100000, 100000, 100000, 100000, 100000, 2784, 100000, 100000, 100000, 100000, 100000, 100000, 2784)]
```

**Comment by JonahDW** [comment]
The problem persists using the `auto-bounds` branch, unfortunately.

**Comment by o-smirnov** [comment]
Can I get hold of the MS somehow?

**Comment by IanHeywood** [comment]
> Did you drop completely flagged rows when the MS was averaged / split?

Can confirm that this isn't the issue.

**Comment by JonahDW** [comment]
> Can I get hold of the MS somehow?
I can't share the data unfortunately.

**Comment by o-smirnov** [comment]
Maybe you can split out a very small chunk of the band, and if the problem persists there, share that?

**Comment by IanHeywood** [comment]
Or if it's proprietary just scramble the data column.

**Comment by o-smirnov** [comment]
Yeah that's true, the error should occur whatever the data values are. Just split out a small subset and write zeroes to the DATA? Or just split MODEL_DATA out, unless the model is proprietary too?

**Comment by JonahDW** [comment]
Okay, I've now split out a portion of the band and set all data to ones, and the same error is still produced. The ms located on our ftp server at:
[ftp://ftp.mpifr-bonn.mpg.de/outgoing/wagenveld/dasktest.ms.tar.gz](url)

Hope that helps

**Comment by o-smirnov** [comment]
Odd, I can run it just fine:
```
shadems --xaxis FREQ --yaxis CORRECTED_DATA:amp --colour-by BASELINE dasktest.ms
2020-05-04 12:35:01 - shadems - INFO - /home/oms/.venv/sms/bin/shadems --xaxis FREQ --yaxis CORRECTED_DATA:amp --colour-by BASELINE dasktest.ms
2020-05-04 12:35:01 - shadems - INFO - ------------------------------------------------------
2020-05-04 12:35:01 - shadems - INFO - : MS dasktest.ms contains 602784 rows
2020-05-04 12:35:01 - shadems - INFO - :   (1, 11) spectral windows and channels
2020-05-04 12:35:01 - shadems - INFO - :   1 fields: J1833-2103
2020-05-04 12:35:01 - shadems - INFO - :   1 scans, first #2, last #2
2020-05-04 12:35:01 - shadems - INFO - :   63 antennas: 0:m000 1:m001 2:m002 3:m003 4:m004 5:m005 6:m006 7:m007 8:m008 9:m009 10:m010 11:m011 12:m012 13:m013 14:m014 15:m015 16:m016 17:m017 18:m018 19:m019 20:m020 21:m021 22:m022 23:m023 24:m024 25:m025 26:m026 27:m027 28:m028 29:m029 30:m030 31:m031 32:m032 33:m033 34:m034 35:m035 36:m036 37:m037 38:m038 39:m039 40:m040 41:m041 42:m042 43:m043 44:m044 45:m045 46:m046 47:m047 48:m048 49:m049 50:m050 51:m051 52:m053 53:m054 54:m055 55:m056 56:m057 57:m058 58:m059 59:m060 60:m061 61:m062 62:m063
2020-05-04 12:35:01 - shadems - INFO - :   corrs/Stokes XX YY I Q
2020-05-04 12:35:01 - shadems - INFO - ------------------------------------------------------
2020-05-04 12:35:01 - shadems - INFO - : Data selected for plotting:
2020-05-04 12:35:01 - shadems - INFO - Antenna(s)       : all
2020-05-04 12:35:01 - shadems - INFO - Baseline(s)      : all
2020-05-04 12:35:01 - shadems - INFO - Field(s)         : all
2020-05-04 12:35:01 - shadems - INFO - SPW(s)           : all
2020-05-04 12:35:01 - shadems - INFO - Scan(s)          : all
2020-05-04 12:35:01 - shadems - INFO - Channels         : all
2020-05-04 12:35:01 - shadems - INFO - Corr/Stokes      : XX YY
2020-05-04 12:35:01 - shadems - INFO - ------------------------------------------------------
2020-05-04 12:35:01 - shadems - INFO - axis: FREQ, range (None, None), discretization None
2020-05-04 12:35:01 - shadems - INFO - axis: amp(CORRECTED_DATA), corr None, range (None, None), discretization None
2020-05-04 12:35:01 - shadems - INFO - axis: BASELINE, range (None, None), discretization 16
2020-05-04 12:35:01 - shadems - INFO -                  : you have asked for 1 plots employing 3 unique datums
2020-05-04 12:35:01 - shadems - INFO - : Indexing MS and building dataframes (602784 rows, chunk size is 5000)
2020-05-04 12:35:01 - shadems - INFO - : complete
2020-05-04 12:35:01 - shadems - INFO - : rendering 1 dataframes with 1.33e+07 points into 1 plot types
2020-05-04 12:35:01 - shadems - INFO - : rendering plot-dasktest-CORRECTED_DATA-XX-YY-amp-FREQ-BASELINE.png
2020-05-04 12:35:01 - shadems - INFO - : scanning axis min/max for _FREQ_False CORRECTED_DATA_amp_None _BASELINE_False
2020-05-04 12:35:17 - shadems - INFO - : rendering using 16 colors (values +0 +1 +2 +3 +4 +5 +6 +7 +8 +9 +10 +11 +12 +13 +14 +15)
2020-05-04 12:35:18 - shadems - INFO -                  : wrote plot-dasktest-CORRECTED_DATA-XX-YY-amp-FREQ-BASELINE.png
2020-05-04 12:35:18 - shadems - INFO - Total time       : 17.08 seconds
2020-05-04 12:35:18 - shadems - INFO - Finished
2020-05-04 12:35:18 - shadems - INFO - ------------------------------------------------------
```
![image](https://user-images.githubusercontent.com/6470079/80957913-64c70780-8e04-11ea-8403-204757c1487c.png)

And I tried different chunk sizes and everything. Are you sure you tried the latest ``auto-bounds`` branch? Also what are your dask-ms and datashader versions? Mine are

```
dask              2.14.0                  
dask-ms           0.2.3                   /scratch/oms/projects/dask-ms   
```
...and datashader is the ``o-smirnov`` fork, master branch.

**Comment by JonahDW** [comment]
Thanks for testing this. Turns out I had to update a whole bunch of stuff, most importantly datashader. It works now, though me trying to color by baseline was a bit much for my memory anyway, as the process gets killed.

**Comment by o-smirnov** [comment]
You can try to lower the chunk size with e.g. ``-z 1000``. This can lower memory use (to an extent...) We're not adjusting that automatically yet.
