### ISSUE TITLE
DistributionNotFound after pip install 

### ISSUE THREAD

**Issue by sarrvesh** [ratt-ru/shadeMS#83]
When I run `shadems --help`, I get 

```
Traceback (most recent call last):
  File "/usr/local/bin/shadems", line 4, in <module>
    __import__('pkg_resources').require('shadems==0.4.0')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'shadems==0.4.0' distribution was not found and is required by the application
```

When I do, `pip3 show shadems`, I get `WARNING: Package(s) not found: shadems` but works fine for everything else that was installed with pip3 (like numpy or scipy). Clearly, something is wrong with the installation or the environment. 

I am using Ubuntu 18.04 with python 3.6 and pip3 20.2.4. I followed the standard installation instruction from readme and installation went fine. The installation log is available here: [log](https://pastebin.com/ZtsTSrRp). 

Am I missing something?

**Comment by o-smirnov** [comment]
Yeah that's pretty weird, the install log looks just fine. Could you try two things to see if they make a difference:

* install into a virtualenv

* checkout the ``b050`` branch and install that (it's a better branch to use anyway)

**Comment by sarrvesh** [comment]
Ah, my bad. The problem is in my installation script. I was deleting the cloned GitHub repo while cleaning up all the build directories. Apologies for the noise and thanks for suggesting the `b050' branch. Will try it out.

**Comment by o-smirnov** [comment]
b050 is now on master -- going to make a 0.5.0 release shortly.
